# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default=b'\xe6\x97\xa0\xe6\xa0\x87\xe9\xa2\x98', max_length=200),
        ),
    ]
